languages: bash
services: docker
before_install:
  - cd 15\ RestWithSpringBootUdemy\ Scaffold\ docker/
  - echo "We are in the docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push ddn19/mysql-rest-with-spring-boot-udemy;
    docker push ddn19/rest-with-spring-boot-udemy;
  on:
    branch: main
notifications:
  email: false